In [13]:
import torch

In [15]:
x = torch.rand(3,3)
x

tensor([[0.1763, 0.9439, 0.9882],
        [0.6122, 0.1978, 0.0414],
        [0.8799, 0.2213, 0.8035]])

## 输出tensor的各种属性

In [22]:

print(x.device)
print(x.dtype)
print(x.data)
print(x.grad)
print(x.ndim)

cpu
torch.float32
tensor([[0.1763, 0.9439, 0.9882],
        [0.6122, 0.1978, 0.0414],
        [0.8799, 0.2213, 0.8035]])
None
2


## tensor 的存储布局

在内存中， tensor 是按照一维数组的形式存储的。在执行 view 的时候，按照一定的格式呈现给使用者。比如创建一个 (3,4,2) 的 tensor, 内存中就会开辟一个能够存储 $3*4*2$ = 24 个 value 的数组。 使用 stride 控制 tensor 访问时的数据分配。 (3,4,2) 的 tensor 要想正常呈现， 需要有 (4*2, 2, 1) 的 stride. stride 值得是每一个维度相邻元素之间的间隔。 (3,4,2) 的 x, x[i][j][k] 和 x[i+1][j][k] 之间相差就有 8 个元素， 而 x[i][j][k] 和 x[i][j+1][k] 之间相差只有 2 个元素。

In [24]:
print(x)
# 因为 stride 设置成 (1, 2) 所以
print(torch.as_strided(x, (2, 2), (1, 2)))
print(torch.as_strided(x, (2, 2), (1, 2), 1))


tensor([[0.1763, 0.9439, 0.9882],
        [0.6122, 0.1978, 0.0414],
        [0.8799, 0.2213, 0.8035]])
tensor([[0.1763, 0.9882],
        [0.9439, 0.6122]])
tensor([[0.9439, 0.6122],
        [0.9882, 0.1978]])
