In [1]:
import torch

## create sparse tensor

In [2]:
indices = [[0,2], [1,0], [1,2]]
values = [3,4,5]
x = torch.sparse_coo_tensor(torch.tensor(indices).T, values, size=(2,3))
print(x)
print(x.to_dense())

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)
tensor([[0, 0, 3],
        [4, 0, 5]])


## create sequences

In [9]:
print(torch.arange(start=1, end=4, step=0.5))
# torch.range() will be deprecated
# print(torch.range(start=1, end=4, step=0.5))
print(torch.linspace(start=3, end=10, steps=5))
print(torch.logspace(start=-10, end=10, steps=5))
print(torch.logspace(start=0, end=4, steps=5, base=2))

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])
tensor([ 1.,  2.,  4.,  8., 16.])


## 值填充

In [11]:
torch.full(size=(2, 3), fill_value=3.14)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

## Indexing, Slicing, Joining, Mutating Ops

In [13]:
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.4725, 0.1082, 0.6939],
        [0.1298, 0.0333, 0.1883],
        [0.2985, 0.6423, 0.9982]])
tensor([[0.8655, 0.2275, 0.0999],
        [0.9105, 0.6720, 0.2437],
        [0.2535, 0.1020, 0.5348]])


In [14]:
z = torch.cat((x, y), dim=0)
print(z)
z = torch.cat((x, y), dim=1)
print(z)

tensor([[0.4725, 0.1082, 0.6939],
        [0.1298, 0.0333, 0.1883],
        [0.2985, 0.6423, 0.9982],
        [0.8655, 0.2275, 0.0999],
        [0.9105, 0.6720, 0.2437],
        [0.2535, 0.1020, 0.5348]])
tensor([[0.4725, 0.1082, 0.6939, 0.8655, 0.2275, 0.0999],
        [0.1298, 0.0333, 0.1883, 0.9105, 0.6720, 0.2437],
        [0.2985, 0.6423, 0.9982, 0.2535, 0.1020, 0.5348]])


In [21]:
print(torch.chunk(x, 3, 1))
print(torch.chunk(x, 2, 0))

(tensor([[0.4725],
        [0.1298],
        [0.2985]]), tensor([[0.1082],
        [0.0333],
        [0.6423]]), tensor([[0.6939],
        [0.1883],
        [0.9982]]))
(tensor([[0.4725, 0.1082, 0.6939],
        [0.1298, 0.0333, 0.1883]]), tensor([[0.2985, 0.6423, 0.9982]]))


In [26]:
x = torch.rand(3, 6)
x

tensor([[0.6278, 0.4093, 0.9885, 0.1225, 0.4257, 0.2982],
        [0.1549, 0.7886, 0.9943, 0.0656, 0.6208, 0.4432],
        [0.9040, 0.4780, 0.3560, 0.4858, 0.2787, 0.4405]])

In [30]:
print(torch.tensor_split(x, 3, dim=1))
print(torch.tensor_split(x, 3, dim=0))
print(torch.tensor_split(x, [1,4], dim=1))

(tensor([[0.6278, 0.4093],
        [0.1549, 0.7886],
        [0.9040, 0.4780]]), tensor([[0.9885, 0.1225],
        [0.9943, 0.0656],
        [0.3560, 0.4858]]), tensor([[0.4257, 0.2982],
        [0.6208, 0.4432],
        [0.2787, 0.4405]]))
(tensor([[0.6278, 0.4093, 0.9885, 0.1225, 0.4257, 0.2982]]), tensor([[0.1549, 0.7886, 0.9943, 0.0656, 0.6208, 0.4432]]), tensor([[0.9040, 0.4780, 0.3560, 0.4858, 0.2787, 0.4405]]))
(tensor([[0.6278],
        [0.1549],
        [0.9040]]), tensor([[0.4093, 0.9885, 0.1225],
        [0.7886, 0.9943, 0.0656],
        [0.4780, 0.3560, 0.4858]]), tensor([[0.4257, 0.2982],
        [0.6208, 0.4432],
        [0.2787, 0.4405]]))
